### ISSUE TITLE
Has anyone been successful building in Linux?

### ISSUE THREAD

**Issue by AgileEngineeringLLC** [taroz/GNSS-SDRLIB#16]
Has anyone built Gnss-sdrlib in Linux, say Ubuntu? If so, what mods did you make to get it to work? thx!

**Comment by Strykar** [comment]
Quite unlikely, last update was six years ago and read https://github.com/taroz/GNSS-SDRLIB#system-requirements

**Comment by AgileEngineeringLLC** [comment]
Saw that, but I'm working on it now and just curious if anyone else has tried. The developers apparently attempted the CLI build in Linux, but noted that they had some issues. Seems like it should port over, much like the RTKLIB code has now.

**Comment by AgileEngineeringLLC** [comment]
Update... I have it ported over to Ubuntu now, runs fairly well, but still will require updates to a number of the h files and libs to bring them up-to-date from 2016 timeframe.

**Comment by andrecc-7** [comment]
`gcc -o gnss-sdrcli sdrmain.o sdrcmn.o sdracq.o sdrcode.o sdrinit.o sdrnav.o sdrnav_gps.o sdrnav_glo.o sdrnav_gal.o sdrnav_bds.o sdrnav_sbs.o sdrout.o sdrplot.o sdrrcv.o sdrspec.o sdrtrk.o sdrlex.o sdrsync.o stereo.o rtkcmn.o rtcm.o rtcm2.o rtcm3.o rtcm3e.o rinex.o -Wall -O3 -march=native -I../../src -I../../lib/rtklib -I../../lib/fec -I../../src/rcv/stereo -I../../src/rcv/rtlsdr -I../../src/rcv/bladerf -DSSE2_ENABLE -DFFTMTX -DSTEREO -DSTEREOV26 -g -lm -lrt -lfftw3f -lfftw3f_threads -lpthread ../../src/rcv/stereo/linux/libnslstereo.a ../../lib/fec/linux/libfec.a -lusb-1.0
/usr/bin/ld: ../../src/rcv/stereo/linux/libnslstereo.a(stereo_usb_STA.o): relocation R_X86_64_PC32 against symbol `libusb_open' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../src/rcv/stereo/linux/libnslstereo.a(stereo_cfg_STA.o): relocation R_X86_64_PC32 against symbol `libusb_control_transfer' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../src/rcv/stereo/linux/libnslstereo.a(usb_api_lin_STA.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/fec/linux/libfec.a(viterbi27_port.o): relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/fec/linux/libfec.a(decode_rs_ccsds.o): relocation R_X86_64_32S against symbol `Tal1tab' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/fec/linux/libfec.a(fec.o): relocation R_X86_64_32 against symbol `Partab' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: ../../lib/fec/linux/libfec.a(decode_rs_8.o): relocation R_X86_64_32S against symbol `CCSDS_index_of' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [makefile:46: gnss-sdrcli] Error 1`

The flag '-no-pie' solved this for me, instead of '-fPIC'.

**Comment by andreisilv** [comment]
> /usr/bin/ld: ../../lib/fec/linux/libfec.a(decode_rs_8.o): relocation R_X86_64_32S against symbol `CCSDS_index_of' can not be used when making a PIE object; recompile with -fPIC

If you encountered the same error as me. The flag '-no-pie' solved it, instead of '-fPIC'.

**Comment by Strykar** [comment]
> Update... I have it ported over to Ubuntu now, runs fairly well, but still will require updates to a number of the h files and libs to bring them up-to-date from 2016 timeframe.

Nice work! I don't see your fork though.

**Comment by Jaeyoung-Lim** [comment]
@AgileEngineeringLLC Awesome! 

Could you provide more information?  Would it be possible to get your changes public on a possible fork? Would be awesome if we can get this running on linux

**Comment by AgileEngineeringLLC** [comment]
Sorry, have not worked on this for quite a while. You might check out the 15 or so articles on my linkedIn account, might be something there to help. If I recall, I ended up removing all the WIN stuff, removed all the outdated SDR hardware stuff, added any missing libs, then just kept tweaking the h files until it worked.

LinkedIn: www.linkedin.com/in/kellydak

**Comment by Jaeyoung-Lim** [comment]
@AgileEngineeringLLC Thanks for the update!
